C = require('./Card');

let f3_0 = 
   [new C.DrawRule("Draw 2", 2),
	new C.DrawRule("Draw 3", 3),
	new C.DrawRule("Draw 4", 4),
	new C.DrawRule("Draw 5", 5),
	new C.PlayRule("Play 2", 2),
	new C.PlayRule("Play 3", 3),
	new C.PlayRule("Play 4", 4),
	new C.PlayRule("Play All", Number.MAX_SAFE_INTEGER),
	new C.HLimRule("Hand Limit 0", 0),
	new C.HLimRule("Hand Limit 1", 1),
	new C.HLimRule("Hand Limit 2", 2),
	new C.KLimRule("Keeper Limit 2", 2),
	new C.KLimRule("Keeper Limit 3", 3),
	new C.KLimRule("Keeper Limit 4", 4),
	new C.NRule("Double Agenda"),
	new C.NRule("Reverse Order"),
	new C.NRule("First Play Random"),
	new C.NRule("No-Hand Bonus"),
	new C.NRule("Poor Bonus"),
	new C.NRule("Rich Bonus"),
	new C.NRule("Double Agenda"),
	new C.Action("Discard and Draw", actions[0]),
	new C.Action("Draw 2 & Use 'Em", actions[1]),
	new C.Action("Draw 3, Play 2", actions[2]),
	new C.Action("Empty the Trash", actions[3]),
	new C.Action("Everybody Gets 1", actions[4]),
	new C.Action("Exchange Keepers", actions[5]),
	new C.Action("Go Fish", actions[6]),
	new C.Action("I Need a Goal", actions[7]),
	new C.Action("Let's Do That Again", actions[8]),
	new C.Action("Let's Simplify", actions[9]),
	new C.Action("No Limits", actions[10]),
	new C.Action("Rotate Hands", actions[11]),
	new C.Action("Rules Reset", actions[12]),
	new C.Action("Scramble Keepers", actions[13]),
	new C.Action("Steal a Keeper", actions[14]),
	new C.Action("Take Another Turn", actions[15]),
	new C.Action("Taxation", actions[16]),
	new C.Action("Trade Hands", actions[17]),
	new C.Action("Trash a Keeper", actions[18]),
	new C.Action("Trash a New Rule", actions[19]),
	new C.Action("Use What You Take", actions[20]),
	new C.Keeper("The Brain", 0),
	new C.Keeper("Bread", 1),
	new C.Keeper("Chocolate", 2),
	new C.Keeper("Cookies", 3),
	new C.Keeper("Death", 4),
	new C.Keeper("Dreams", 5),
	new C.Keeper("Love", 6),
	new C.Keeper("Milk", 7),
	new C.Keeper("Money", 8),
	new C.Keeper("The Moon", 9),
	new C.Keeper("Peace", 10),
	new C.Keeper("Rocket", 11),
	new C.Keeper("Sleep", 12),
	new C.Keeper("The Sun", 13),
	new C.Keeper("Television", 14),
	new C.Keeper("Time", 15),
	new C.Keeper("The Toaster", 16),
	new C.Keeper("War", 17),
	new C.SpecialGoal("10 Cards in Hand", function() {console.log("TODO")}),
	new C.SpecialGoal("5 Keepers", function() {console.log("TODO")}),
	new C.SpecialGoal("All You Need is Love", function() {console.log("TODO")}),
	new C.TwoKeep("The Appliances", [14, 16]),
	new C.TwoKeep("Baked Goods", [1, 3]),
	new C.TwoKeep("Bed Time", [12, 15]),
	new C.OneKeep("The Brain (no TV)", [0, 14]),
	new C.TwoKeep("Chocolate Cookies", [2, 3]),
	new C.TwoKeep("Chocolate Milk", [2, 7]),
	new C.TwoKeep("Death by Chocolate", [2, 4]),
	new C.TwoKeep("Dreamland", [5, 12]),
	new C.TwoKeep("Hearts and Minds", [0, 6]),
	new C.TwoKeep("Hippyism", [6, 10]),
	new C.TwoKeep("Milk and Cookies", [3, 7]),
	new C.TwoKeep("Night and Day", [9, 13]),
	new C.OneKeep("Peace (no War)", [10, 17]),
	new C.TwoKeep("Rocket Science", [3, 7]),
	new C.TwoKeep("Rocket to the Moon", [0, 11]),
	new C.TwoKeep("Squishy Chocolate", [2, 13]),
	new C.TwoKeep("Time is Money", [8, 15]),
	new C.TwoKeep("Toast", [1, 16]),
	new C.TwoKeep("War = Death", [4, 17]),
	new C.TwoKeep("Winning the Lottery", [5, 8])];

export *;